name: Run CI/CD Workflow
on:
  workflow_dispatch:  
#   push:
#     branches: [main, develop]
#   pull_request:
#     branches: [main, develop]
jobs:
  formatting-check:
    name: clang-foramt Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - check: 'src'
            exclude: ''              # Nothing to exclude
          - check: 'test'
            exclude: '(template|unity|hw_test)'  # Exclude file paths containing "template" or "unity"

    steps:
    - uses: actions/checkout@v4.1.1
    - name: Run clang-format style check for C/C++/Protobuf programs.
      uses: jidicula/clang-format-action@v4.11.0
      with:
        clang-format-version: '17'
        check-path: ${{ matrix.path['check'] }}
        exclude-regex: ${{ matrix.path['exclude'] }}
        # fallback-style: 'Microsoft' # optional
  cppcheck-annotations_scr:
    name: cppcheck /src
    needs: formatting-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Run cppcheck-annotation-action for src
        uses: Konstantin343/cppcheck-annotation-action@v1.0
        with:
          std: 'c99'
          platform: 'unix64'
          log-level: 'verbose'
          sources: './src'
          annotation-failures: 'warning'
          # suppress: 'unusedFunction'
          # annotation-level-default: 'error'
      - name: Annotate lines with errors src
        uses: yuzutech/annotations-action@v0.4.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          title: 'Results of CppCheck src files'
          input: 'annotations.json'
      - name: Run cppcheck /tests
        uses: Konstantin343/cppcheck-annotation-action@v1.0
        with:
          std: 'c99'
          platform: 'unix64'
          log-level: 'verbose'
          sources: './test/template'
          annotation-failures: 'warning'
          # suppress: 'unusedFunction'
          # annotation-level-default: 'error'
      - name: Annotate lines with errors test_src
        uses: yuzutech/annotations-action@v0.4.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          title: 'Results of CppCheck test lcd_hd44780 files'
          input: 'annotations.json'